import { useGetProductsQuery } from "@generated/api";
import Image from "next/image";
import Link from "next/link";
import { numberOfProducts } from "@utils/utils";

type ProductsProps = {
  keyword: string;
};

export default function Products({ keyword }: ProductsProps) {
  // Autogenerated hook for products, thanks to api.ts
  const { loading, error, data } = useGetProductsQuery({
    variables: {
      first: numberOfProducts,
      filter: { search: keyword },
    },
  });

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error</p>;

  if (data) {
    const products = data.products?.edges || [];

    return (
      <ul>
        {products?.length > 0 &&
          products.map(({ node: { id, name, thumbnail, category, description, slug } }) => {
            return (
              <li key={id}>
                <a>
                  <div>
                    <p>{name}</p>
                    <p>{category?.name}</p>
                    {/* <p>{description}</p> */}
                  </div>
                </a>
                <Image width={200} height={200} src={thumbnail?.url} alt={name as string} />
                <Link href={`/product/${slug}`}>more</Link>
              </li>
            );
          })}
      </ul>
    );
  }

  return null;
}
