import Head from "next/head";
import Products from "@components/products/Products";
import Layout from "@components/layout/Layout";
import Hero from "@components/hero/Hero";

type NavigationProps = {
  keyword: string;
};

export default function Home({ keyword }: NavigationProps) {
  return (
    <>
      <Head>
        <title>Posh E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <Products keyword={keyword} />
      </Layout>
    </>
  );
}
