import { useState } from "react";
import Head from "next/head";
import Products from "@components/products/Products";
import SearchBar from "@components/search-bar/SearchBar";

export default function Home() {
  const [keyword, setKeyword] = useState<string>("");


  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main>
        <SearchBar onSetKeyword={setKeyword} />
        <Products keyword={keyword} />
      </main>
    </>
  );
}
